### ISSUE TITLE
source repo has updated commits

### ISSUE THREAD

**Issue by tcheinen** [web-extensions-rs/web-extensions-sys#1]
hey! I don't know if you're still updating this but the source repo (tab organizer) has a [pretty hefty commit related to themes](https://github.com/Pauan/tab-organizer/commit/49026f529492b352003ac4fe19c33cc7f9ffb19b#diff-f0503694ea1d0a9e2373586d3b8a346c4f04f133dccb611fa05bc00d825a81d0). Might be worth pulling that in and pushing to crates.io.

**Comment by rvolosatovs** [comment]
For now the work on this is paused on my side due to health issues, but I will be happy to take a look if there is demand.
PRs always welcome as well :)
