### ISSUE TITLE
Way to make local/session part of storage

### ISSUE THREAD

**Issue by eugenesvk** [web-extensions-rs/web-extensions-sys#23]
Is it possible to use various `Storage` variants in a similar way to how Gloo storage exposes Web storage APIs, where these variants are of the same shared `Storage` type?

For example, [gloo storage lib](https://github.com/rustwasm/gloo/blob/8ea0bea55df2156f608708e5b272f03d606f00d1/crates/storage/src/lib.rs#L28) implements a common Storage trait with this raw associated function that returns a general `Storage` type
```rs
pub trait Storage {
  fn raw() -> web_sys::Storage;

```
and then this `Storage` type works for both [session](https://github.com/rustwasm/gloo/blob/master/crates/storage/src/session_storage.rs)
```rs
impl Storage for SessionStorage {
  fn raw() -> web_sys::Storage {
    web_sys::window()
//...
      .session_storage()
```

 and [local](https://github.com/rustwasm/gloo/blob/master/crates/storage/src/local_storage.rs) storage
```rs
impl Storage for LocalStorage {
  fn raw() -> web_sys::Storage {
    web_sys::window()
//...
      .local_storage()
```
since `web_sys::window()` `.session_storage()` and `.local_storage()` return type `Storage`

However, `web-extensions-rs` has different types (`Local` for local storage and `SessionStorage` for session storage), so this doesn't work and `pub trait Storage {` has to be duplicated so that `fn raw()` returns a specific type instead of a more general `web_extensions_sys::Storage`
Or maybe there is also a simple way to achieve it here as well that I'm just not aware of?
Thanks!

P.S.
Replacing `pub type Sync`, `pub type Local`,  `pub type SessionStorage` (but not `Managed` since it doesn't implement `StorageAreaWrite`) with a single name like `StorageCommon` seems to work — I'm able to achieve the same gloo-like use convenience as described above, but then I'm not sure whether there are some substantial benefits to this separation

**Comment by eugenesvk** [comment]
@Pauan since you seem to be the original author of these webext storage bindings, would you kindly explain why there are concrete types for various webext Storage Areas (local/session/sync) instead of a shared type just like in `web_sys` bindings and whether it would make sense to combine them for the benefits described above? Thank you!

**Comment by Pauan** [comment]
What do you mean? There is no `SessionStorage`. And there already exists a common shared type, it's [`StorageAreaWrite`](https://github.com/web-extensions-rs/web-extensions-sys/blob/65510e2f241802a11e7ec826dcb80767bb6b8ae6/src/storage.rs#L21) (or [`StorageAreaRead`](https://github.com/web-extensions-rs/web-extensions-sys/blob/65510e2f241802a11e7ec826dcb80767bb6b8ae6/src/storage.rs#L8) for read-only methods).

**Comment by eugenesvk** [comment]
> There is no `SessionStorage`

I've added it, see this https://github.com/web-extensions-rs/web-extensions-sys/pull/22, but it can be ignored, the `Sync` similarly can't be "grouped" with `Local`

> And there already exists a common shared type,

it doesn't work since `pub fn local(this: &Storage) -> Local;`, so this leads to a type mismatch (expected `StorageAreaWrite`, found struct `Local`)
```rs
impl Storage for LocalStorage {
  fn raw() -> web_extensions_sys::StorageAreaWrite {
    web_extensions_sys::browser
      .storage()
      .local()
```

If instead all those concrete types for various storage areas were simply `StorageAreaWrite` (e.g., pub `fn local(this: &Storage) -> StorageAreaWrite;`), then yes, that would work.
Hence my question about why there is a further subdivision of types

Or maybe there is a different way to make
```rs
pub trait Storage {
  fn raw () -> web_extensions_sys::StorageAreaWrite;
```
work to accept `Local` and `Sync` and `SessionStorage` that extend `StorageAreaWrite` without any changes in this crate?

**Comment by Pauan** [comment]
wasm-bindgen types implement coercion traits, so something like this should work:

```rust
impl<A> Storage for A where A: Into<web_extensions_sys::StorageAreaWrite> {
  fn raw() -> web_extensions_sys::StorageAreaWrite {
    web_extensions_sys::browser
      .storage()
      .local()
      .into()
```

Though I can't think of any particular reason to have separate types, so having them return `StorageAreaWrite` sounds fine to me.

Perhaps it would also be a good idea to rename them, so it would be `StorageAreaRead` and `StorageArea`, and then it can return `StorageArea`:

```rust
#[wasm_bindgen]
extern "C" {
    pub type Storage;

    #[wasm_bindgen(method, getter)]
    pub fn sync(this: &Storage) -> StorageArea;

    #[wasm_bindgen(method, getter)]
    pub fn local(this: &Storage) -> StorageArea;

    #[wasm_bindgen(method, getter)]
    pub fn managed(this: &Storage) -> StorageAreaRead;

    #[wasm_bindgen(method, getter, js_name = onChanged)]
    pub fn on_changed(this: &Storage) -> EventTarget;
}
```

**Comment by eugenesvk** [comment]
> wasm-bindgen types implement coercion traits, so something like this should work:

thanks for the tip, this does indeed work (is my understanding correct that this explicit extension `#[wasm_bindgen(extends = StorageAreaWrite)] pub type Local;` ensures that your type coercion will always work)?

> Though I can't think of any particular reason to have separate types, so having them return `StorageAreaWrite` sounds fine to me.

though I also think this is a cleaner option

**Comment by Pauan** [comment]
> is my understanding correct that this explicit extension `#[wasm_bindgen(extends = StorageAreaWrite)] pub type Local;` ensures that your type coercion will always work

Yes, [`extends` creates `AsRef`, `AsMut`, `From`, `Into`, and `Deref` impls](https://rustwasm.github.io/docs/wasm-bindgen/reference/attributes/on-js-imports/extends.html).

Because it creates a `Deref` impl, that means this works:

```rust
fn foo(storage: &StorageAreaWrite) { ... }

foo(&browser.storage().local());
foo(&browser.storage().sync());
```

And since `Deref` is recursive, even this works:

```rust
fn foo(storage: &StorageAreaRead) { ... }

foo(&browser.storage().local());
foo(&browser.storage().sync());
foo(&browser.storage().managed());
```
