### ISSUE TITLE
How to use `sys::chrome()` ?

### ISSUE THREAD

**Issue by TieWay59** [web-extensions-rs/web-extensions-sys#44]
I'm trying to write some equivalent code to:

```js
chrome.action.onClicked.addListener((tab) => {
    // ...
});
```
And I use the API like this:

![image](https://user-images.githubusercontent.com/40034603/204029654-35e88ae8-d582-49dc-a8e8-be65f383ceee.png)
 
It's not what I expect because this `chrome()` returns one `JsStatic<Browser>` object and it shows no member API. I wish to know what steps did I miss.

I'm new to this area, and this may be a very naive question. But I have done my research and still have no clue about it. 

Many thanks in advance.

**Comment by flosse** [comment]
Could you share some code that don't compile?
Your IDE might not able to show you the correct API.

**Comment by TieWay59** [comment]
The reason for this issue is that the history feature is not enabled.
